[project]
name = "morph-gen"
version = "0.1.0"
description = "генерация карт замен с формефами"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.8.9",
    "pymorphy3>=2.0.6",
    "pymorphy3-dicts-ru>=2.4.417150.4580142",
    "pyyaml>=6.0.3",
]
